In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [22]:
def ReLu(x):
    # if (x < 0):
    #     return 0
    # return x
    return np.maximum(0,x)

def softmax(x):
    sum = 0
    for i in range(len(x)):
        sum += np.exp(x[i])
    return np.exp(x) / sum


# def Max3x3(M): // a adapter car pour le moment j'utilise  np.max ca fait le taff
#     max = M[0][0]
#     for i in range(3):
#         for j in range(3):
#             if M[i][j] > max:
#                 max = M[i][j]
#     return max

def MaxPool(M):
    y,x,num_channels = M.shape
    i = 0
    j = 0
    output_height = (y - 3) // 2 + 1
    output_width = (x - 3) // 2 + 1
    output = np.zeros((output_height, output_width, num_channels))

    for c in range(num_channels):
        for i in range(0, output_height):
            for j in range(0, output_width):
                start_i, start_j = i * 2, j * 2
                region = M[start_i:start_i + 3, start_j:start_j + 3, c] #j'ai enlever output x et y car pas besoin et re for pour eviter de remettre à 0
                output[i, j, c] = np.max(region)
 
    return output

def convolution(image, Ks, biais):
    image_height, image_width, image_channels = image.shape
    num_filters, K_height, K_width, _ = Ks.shape
    output_height = image_height
    output_width = image_width
    output = np.zeros((output_height, output_width, num_filters))
    padded_image = np.pad(image, ((1, 1), (1, 1), (0, 0)), mode='constant') #j'ai vu qu'il fallait faire du padding pour conserver les dimensions de notre frame 3D 
   
    for f in range(num_filters):
        conv_sum = np.zeros((output_height, output_width))
        for c in range(image_channels):  
            for i in range(output_height):
                for j in range(output_width):
                    region = padded_image[i:i+K_height, j:j+K_width, c]
                    conv_sum[i, j] += np.sum(region * Ks[f, :, :, c])
        output[:, :, f] = ReLu(conv_sum + biais[f])
   
    return output

def reshape(M):
    output = np.array([])

In [3]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [20]:

matrice = np.random.randint(0, 256, size=(24, 24, 3))

R = matrice[:, :, 0]
G = matrice[:, :, 1]
B = matrice[:, :, 2]

print("Canal Rouge (R):")
print(R)
print("\nCanal Vert (G):")
print(G)
print("\nCanal Bleu (B):")
print(B)


Canal Rouge (R):
[[ 38 158 179 139 109  69 123 136  94  24 217 239 128  65  24 193 126 218
  212  65 219  52 180 155]
 [ 19 164 154  31 135  39 143  11 167  31   4 106 197 121 172  15 240  18
  114  81 239 155  82 140]
 [ 15 146  78 209 134  65 175  49 247  43 252  65 102 172 149  24  96  94
   33 184 160  44 188 125]
 [ 34 157 178  51 180 244 157  35 246  71  90 162  54 188  39   9  61 149
  209 251 139  95 144  15]
 [ 45 207 125 152 244 186  98 236 189  18  38 223  60  86 113 108   6  82
   54 174  18 233 220 220]
 [ 95 199 151 126 113  71  29  30 147 166 175 250 145 247  94 126 194 145
   21  78  58 231 103  73]
 [209  49 190   7  91 183 155   8 184  90  51 250 183 132 181 132   8  20
  250  77 202  52 198  18]
 [143   7   9 158   4 176   8 250 139 187 187 222  47  58 198 219 133 139
   28 192 106 252  26 154]
 [125  24 222 142 232 130 138  14 229 158  20  63 222  89 228 114  45  51
    1 149 120 114 140 146]
 [188 101  38 243 229  47 167 242 154 193  28 105 117  80  84 209 238 235


In [21]:
m2=MaxPool(matrice)
R2 = m2[:, :, 0]
G2 = m2[:, :, 1]
B2 = m2[:, :, 2]

print("Canal Rouge (R):")
print(R2)
print("\nCanal Vert (G):")
print(G2)
print("\nCanal Bleu (B):")
print(B2)

Canal Rouge (R):
[[179. 209. 175. 247. 252. 252. 197. 240. 240. 239. 239.]
 [207. 244. 244. 247. 252. 252. 188. 149. 209. 251. 233.]
 [209. 244. 244. 236. 189. 250. 247. 194. 250. 250. 233.]
 [222. 232. 232. 250. 229. 250. 228. 228. 250. 250. 252.]
 [222. 243. 232. 242. 229. 222. 228. 238. 238. 184. 224.]
 [212. 201. 209. 217. 173. 253. 253. 234. 234. 243. 224.]
 [144. 207. 231. 219. 219. 218. 213. 234. 238. 246. 234.]
 [231. 247. 247. 237. 237. 212. 213. 213. 238. 246. 234.]
 [197. 197. 215. 237. 237. 242. 242. 253. 238. 247. 247.]
 [218. 234. 234. 167. 234. 242. 242. 253. 241. 230. 216.]
 [202. 253. 253. 230. 248. 211. 251. 251. 241. 216. 221.]]

Canal Vert (G):
[[245. 218. 245. 250. 250. 253. 253. 209. 226. 216. 194.]
 [245. 223. 223. 250. 250. 235. 227. 197. 254. 254. 206.]
 [244. 244. 250. 250. 239. 223. 202. 232. 254. 254. 197.]
 [235. 247. 250. 250. 248. 248. 184. 232. 230. 230. 238.]
 [224. 251. 251. 248. 248. 251. 199. 199. 230. 230. 199.]
 [246. 253. 253. 248. 255. 255. 230. 

In [23]:
input_image = np.random.rand(24, 24, 3)
k1 = np.random.rand(64, 3, 3, 3)  # 64 filtres de 3x3x3
biais1 = np.random.rand(64)

conv1_output = convolution(input_image, k1, biais1)
print("Convolution 1 ", conv1_output.shape)  # (24, 24, 64)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()